
>>> call foo (42, 43)
wrong-calls.hlt:7-8: error, too many arguments given, expected 1 but got 2 [pass::Validator]
wrong-calls.hlt: Aborting due to verification error.
error running hiltic, aborting
