
>>> call foo 42
wrong-calls.hlt:12-13: error, operands do not match instruction call
  got:
    call: function(int<32> a) -> void, int<64>
  expected one of:
    call: function() -> void, tuple<*>
    call: function() -> void, tuple<*> -> any
    call: ref<callable<*>>
    call: ref<callable<*>> -> any
 [pass::hilti::InstructionResolver]
wrong-calls.hlt: Aborting due to verification error.
error running hiltic, aborting
