#
# @TEST-EXEC:  hilti-build %INPUT -o a.out
# @TEST-EXEC:  ./a.out >output 2>&1
# @TEST-EXEC:  btest-diff output
#
# These are all supposed to throw exceptions.

module Main

import Hilti

void run() {
    local int<32> i
    local int<64> s
    local ref<list<int<32>>> l
    local iterator<list<int<32>>> c

    l = new list<int<32>>
    list.push_back l 1

    c = begin l
    c = incr c
    list.erase c

}

### @TEST-START-NEXT

module Main

import Hilti

void run() {
    local int<32> i
    local int<64> s
    local ref<list<int<32>>> l
    local iterator<list<int<32>>> c

    l = new list<int<32>>
    list.push_back l 1

    c = begin l
    list.erase c
    list.erase c

}

### @TEST-START-NEXT

module Main

import Hilti

void run() {
    local int<32> i
    local int<64> s
    local ref<list<int<32>>> l
    local iterator<list<int<32>>> c

    l = new list<int<32>>
    list.push_back l 1

    c = begin l
    list.erase c
    c = begin l
    list.erase c

}

### @TEST-START-NEXT

module Main

import Hilti

void run() {
    local int<32> i
    local int<64> s
    local ref<list<int<32>>> l
    local iterator<list<int<32>>> c

    l = new list<int<32>>
    list.push_back l 1

    c = begin l
    list.erase c
    c = incr c

}



