
>>> call foo (x, x)
wrong-calls.hlt:8-9: error, type of parameter 2 does not match function, have int<32> but expected int<16> [pass::hilti::Validator]
wrong-calls.hlt: Aborting due to verification error.
error running hiltic, aborting
